source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.10'
use_frameworks!

target 'CurrencyExchange-Mac' do

pod 'Alamofire'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Masonry'
#pod 'OAStackView'

end

